# main logic script
import subprocess
from pathlib import Path
from itertools import permutations
from wand.image import Image

# --- File Type Mapping ---
file_etx = {
    'img': ['.png', '.apng', '.jpg', '.jpeg', '.jfif', '.pjpeg', '.pjp', '.svg', '.webp', '.gif', '.tif', '.tiff', '.bmp', '.eps', '.heic', '.avif', '.ico', '.cur'],
    'doc': ['.asc', '.doc', '.docx', '.rtf', '.msg', '.pdf', '.txt', '.wpd', '.wps', '.csv', '.xlsx', '.json', '.html', '.htm', '.xhtml', '.asp', '.css', '.aspx', '.rss', '.pptx'],
    'aud': ['.mp3', '.wma', '.snd', '.wav', '.ra', '.au', '.aac'],
    'vid': ['.mp4', '.3gp', '.avi', '.mpg', '.mov', '.wmv'],
}

# --- Functions ---

def choose_file():
    """Open macOS file picker and return a Path object."""
    script = 'set filePath to POSIX path of (choose file with prompt "Select a file:" of type {"public.item"})'
    result = subprocess.run(["osascript", "-e", script], capture_output=True, text=True)
    file_path = result.stdout.strip()

    if result.returncode != 0 or file_path in ("false", ""):
        print("No file selected.")
        return None

    return Path(file_path)


def detect_extension(ext):
    """Check if the given extension exists in exactly one category."""
    ext = ext.lower()
    count = sum(ext in map(str.lower, exts) for exts in file_etx.values())
    return count == 1


def choose_category_and_extension():
    """Ask user to select a file category and corresponding extension."""
    keys = list(file_etx.keys())
    keys_str = ",".join([f'"{k}"' for k in keys])

    ask_category = f'''
    choose from list {{{keys_str}}} with prompt "Select a category:" default items "{keys[0]}"
    '''
    result = subprocess.run(["osascript", "-e", ask_category], capture_output=True, text=True)
    category = result.stdout.strip().strip(',').strip('"')

    if result.returncode != 0 or category in ("false", "") or category not in file_etx:
        print("Cancelled or invalid category.")
        return None, None

    extensions = file_etx[category]
    ext_str = ",".join([f'"{e}"' for e in extensions])

    ask_ext = f'''
    choose from list {{{ext_str}}} with prompt "Select an extension for '{category}':" default items "{extensions[0]}"
    '''
    result = subprocess.run(["osascript", "-e", ask_ext], capture_output=True, text=True)
    extension = result.stdout.strip().strip(',').strip('"')

    if result.returncode != 0 or extension in ("false", "") or extension not in file_etx[category]:
        print("Cancelled or invalid extension.")
        return None, None

    return category, extension


def main():
    print("Select a file to convert:")
    input_path = choose_file()
    if not input_path:
        return

    category, ext = choose_category_and_extension()
    if not category or not ext:
        return

    # Build function name from extensions
    source_ext = input_path.suffix.lstrip('.').lower()
    target_ext = ext.lstrip('.').lower()
    func_name = f"{source_ext}_to_{target_ext}"

    print(f"\nSelected file: {input_path.name}")
    print(f"Converting {source_ext} -> {target_ext} using '{func_name}()' ...")

    # Execute conversion function dynamically
    if func_name in globals():
        output_folder = input_path.parent
        try:
            globals()[func_name](input_path, output_folder)
            print(f"Conversion successful: {input_path.name} → .{target_ext}")
        except Exception as e:
            print(f"Error during conversion: {e}")
    else:
        print(f"Conversion function '{func_name}()' not found in this script.")


# --- img ---

def png_to_apng(input_path: Path, output_folder: Path):
    output_path = output_folder / f"{input_path.stem}.apng"

    cmd = [
        "ffmpeg",
        "-y",
        "-i", str(input_path),
        "-plays", "0",
        str(output_path)
    ]

    try:
        subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        print(f"Converted '{input_path.name}' -> '{output_path.name}'")
    except subprocess.CalledProcessError as e:
        print(f"Conversion failed: {e.stderr.decode('utf-8')}")

def png_to_jpg(input_path: Path, output_folder: Path):
    output_path = output_folder / f"{input_path.stem}.jpg"

    cmd = [
        "ffmpeg",
        "-y",
        "-i", str(input_path),
        "-plays", "0",
        str(output_path)
    ]

    try:
        subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        print(f"Converted '{input_path.name}' -> '{output_path.name}'")
    except subprocess.CalledProcessError as e:
        print(f"Conversion failed: {e.stderr.decode('utf-8')}")

def png_to_jpeg(input_path: Path, output_folder: Path):
    output_path = output_folder / f"{input_path.stem}.jpeg"

    cmd = [
        "ffmpeg",
        "-y",
        "-i", str(input_path),
        "-plays", "0",
        str(output_path)
    ]

    try:
        subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        print(f"Converted '{input_path.name}' -> '{output_path.name}'")
    except subprocess.CalledProcessError as e:
        print(f"Conversion failed: {e.stderr.decode('utf-8')}")
        
def png_to_jfif(input_path: Path, output_folder: Path):
    ...
def png_to_pjpeg(input_path: Path, output_folder: Path):
    ...
def png_to_pjp(input_path: Path, output_folder: Path):
    ...
def png_to_svg(input_path: Path, output_folder: Path):
    ...
def png_to_webp(input_path: Path, output_folder: Path):
    ...
def png_to_gif(input_path: Path, output_folder: Path):
    ...
def png_to_tif(input_path: Path, output_folder: Path):
    ...
def png_to_tiff(input_path: Path, output_folder: Path):
    ...
def png_to_bmp(input_path: Path, output_folder: Path):
    ...
def png_to_eps(input_path: Path, output_folder: Path):
    ...
def png_to_heic(input_path: Path, output_folder: Path):
    ...
def png_to_avif(input_path: Path, output_folder: Path):
    ...
def png_to_ico(input_path: Path, output_folder: Path):
    ...
def png_to_cur(input_path: Path, output_folder: Path):
    ...
def apng_to_png(input_path: Path, output_folder: Path):
    ...
def apng_to_jpg(input_path: Path, output_folder: Path):
    ...
def apng_to_jpeg(input_path: Path, output_folder: Path):
    ...
def apng_to_jfif(input_path: Path, output_folder: Path):
    ...
def apng_to_pjpeg(input_path: Path, output_folder: Path):
    ...
def apng_to_pjp(input_path: Path, output_folder: Path):
    ...
def apng_to_svg(input_path: Path, output_folder: Path):
    ...
def apng_to_webp(input_path: Path, output_folder: Path):
    ...
def apng_to_gif(input_path: Path, output_folder: Path):
    ...
def apng_to_tif(input_path: Path, output_folder: Path):
    ...
def apng_to_tiff(input_path: Path, output_folder: Path):
    ...
def apng_to_bmp(input_path: Path, output_folder: Path):
    ...
def apng_to_eps(input_path: Path, output_folder: Path):
    ...
def apng_to_heic(input_path: Path, output_folder: Path):
    ...
def apng_to_avif(input_path: Path, output_folder: Path):
    ...
def apng_to_ico(input_path: Path, output_folder: Path):
    ...
def apng_to_cur(input_path: Path, output_folder: Path):
    ...
def jpg_to_png(input_path: Path, output_folder: Path):
    ...
def jpg_to_apng(input_path: Path, output_folder: Path):
    ...
def jpg_to_jpeg(input_path: Path, output_folder: Path):
    ...
def jpg_to_jfif(input_path: Path, output_folder: Path):
    ...
def jpg_to_pjpeg(input_path: Path, output_folder: Path):
    ...
def jpg_to_pjp(input_path: Path, output_folder: Path):
    ...
def jpg_to_svg(input_path: Path, output_folder: Path):
    ...
def jpg_to_webp(input_path: Path, output_folder: Path):
    ...
def jpg_to_gif(input_path: Path, output_folder: Path):
    ...
def jpg_to_tif(input_path: Path, output_folder: Path):
    ...
def jpg_to_tiff(input_path: Path, output_folder: Path):
    ...
def jpg_to_bmp(input_path: Path, output_folder: Path):
    ...
def jpg_to_eps(input_path: Path, output_folder: Path):
    ...
def jpg_to_heic(input_path: Path, output_folder: Path):
    ...
def jpg_to_avif(input_path: Path, output_folder: Path):
    ...
def jpg_to_ico(input_path: Path, output_folder: Path):
    ...
def jpg_to_cur(input_path: Path, output_folder: Path):
    ...
def jpeg_to_png(input_path: Path, output_folder: Path):
    ...
def jpeg_to_apng(input_path: Path, output_folder: Path):
    ...
def jpeg_to_jpg(input_path: Path, output_folder: Path):
    ...
def jpeg_to_jfif(input_path: Path, output_folder: Path):
    ...
def jpeg_to_pjpeg(input_path: Path, output_folder: Path):
    ...
def jpeg_to_pjp(input_path: Path, output_folder: Path):
    ...
def jpeg_to_svg(input_path: Path, output_folder: Path):
    ...
def jpeg_to_webp(input_path: Path, output_folder: Path):
    ...
def jpeg_to_gif(input_path: Path, output_folder: Path):
    ...
def jpeg_to_tif(input_path: Path, output_folder: Path):
    ...
def jpeg_to_tiff(input_path: Path, output_folder: Path):
    ...
def jpeg_to_bmp(input_path: Path, output_folder: Path):
    ...
def jpeg_to_eps(input_path: Path, output_folder: Path):
    ...
def jpeg_to_heic(input_path: Path, output_folder: Path):
    ...
def jpeg_to_avif(input_path: Path, output_folder: Path):
    ...
def jpeg_to_ico(input_path: Path, output_folder: Path):
    ...
def jpeg_to_cur(input_path: Path, output_folder: Path):
    ...
def jfif_to_png(input_path: Path, output_folder: Path):
    ...
def jfif_to_apng(input_path: Path, output_folder: Path):
    ...
def jfif_to_jpg(input_path: Path, output_folder: Path):
    ...
def jfif_to_jpeg(input_path: Path, output_folder: Path):
    ...
def jfif_to_pjpeg(input_path: Path, output_folder: Path):
    ...
def jfif_to_pjp(input_path: Path, output_folder: Path):
    ...
def jfif_to_svg(input_path: Path, output_folder: Path):
    ...
def jfif_to_webp(input_path: Path, output_folder: Path):
    ...
def jfif_to_gif(input_path: Path, output_folder: Path):
    ...
def jfif_to_tif(input_path: Path, output_folder: Path):
    ...
def jfif_to_tiff(input_path: Path, output_folder: Path):
    ...
def jfif_to_bmp(input_path: Path, output_folder: Path):
    ...
def jfif_to_eps(input_path: Path, output_folder: Path):
    ...
def jfif_to_heic(input_path: Path, output_folder: Path):
    ...
def jfif_to_avif(input_path: Path, output_folder: Path):
    ...
def jfif_to_ico(input_path: Path, output_folder: Path):
    ...
def jfif_to_cur(input_path: Path, output_folder: Path):
    ...
def pjpeg_to_png(input_path: Path, output_folder: Path):
    ...
def pjpeg_to_apng(input_path: Path, output_folder: Path):
    ...
def pjpeg_to_jpg(input_path: Path, output_folder: Path):
    ...
def pjpeg_to_jpeg(input_path: Path, output_folder: Path):
    ...
def pjpeg_to_jfif(input_path: Path, output_folder: Path):
    ...
def pjpeg_to_pjp(input_path: Path, output_folder: Path):
    ...
def pjpeg_to_svg(input_path: Path, output_folder: Path):
    ...
def pjpeg_to_webp(input_path: Path, output_folder: Path):
    ...
def pjpeg_to_gif(input_path: Path, output_folder: Path):
    ...
def pjpeg_to_tif(input_path: Path, output_folder: Path):
    ...
def pjpeg_to_tiff(input_path: Path, output_folder: Path):
    ...
def pjpeg_to_bmp(input_path: Path, output_folder: Path):
    ...
def pjpeg_to_eps(input_path: Path, output_folder: Path):
    ...
def pjpeg_to_heic(input_path: Path, output_folder: Path):
    ...
def pjpeg_to_avif(input_path: Path, output_folder: Path):
    ...
def pjpeg_to_ico(input_path: Path, output_folder: Path):
    ...
def pjpeg_to_cur(input_path: Path, output_folder: Path):
    ...
def pjp_to_png(input_path: Path, output_folder: Path):
    ...
def pjp_to_apng(input_path: Path, output_folder: Path):
    ...
def pjp_to_jpg(input_path: Path, output_folder: Path):
    ...
def pjp_to_jpeg(input_path: Path, output_folder: Path):
    ...
def pjp_to_jfif(input_path: Path, output_folder: Path):
    ...
def pjp_to_pjpeg(input_path: Path, output_folder: Path):
    ...
def pjp_to_svg(input_path: Path, output_folder: Path):
    ...
def pjp_to_webp(input_path: Path, output_folder: Path):
    ...
def pjp_to_gif(input_path: Path, output_folder: Path):
    ...
def pjp_to_tif(input_path: Path, output_folder: Path):
    ...
def pjp_to_tiff(input_path: Path, output_folder: Path):
    ...
def pjp_to_bmp(input_path: Path, output_folder: Path):
    ...
def pjp_to_eps(input_path: Path, output_folder: Path):
    ...
def pjp_to_heic(input_path: Path, output_folder: Path):
    ...
def pjp_to_avif(input_path: Path, output_folder: Path):
    ...
def pjp_to_ico(input_path: Path, output_folder: Path):
    ...
def pjp_to_cur(input_path: Path, output_folder: Path):
    ...
def svg_to_png(input_path: Path, output_folder: Path):
    ...
def svg_to_apng(input_path: Path, output_folder: Path):
    ...
def svg_to_jpg(input_path: Path, output_folder: Path):
    ...
def svg_to_jpeg(input_path: Path, output_folder: Path):
    ...
def svg_to_jfif(input_path: Path, output_folder: Path):
    ...
def svg_to_pjpeg(input_path: Path, output_folder: Path):
    ...
def svg_to_pjp(input_path: Path, output_folder: Path):
    ...
def svg_to_webp(input_path: Path, output_folder: Path):
    ...
def svg_to_gif(input_path: Path, output_folder: Path):
    ...
def svg_to_tif(input_path: Path, output_folder: Path):
    ...
def svg_to_tiff(input_path: Path, output_folder: Path):
    ...
def svg_to_bmp(input_path: Path, output_folder: Path):
    ...
def svg_to_eps(input_path: Path, output_folder: Path):
    ...
def svg_to_heic(input_path: Path, output_folder: Path):
    ...
def svg_to_avif(input_path: Path, output_folder: Path):
    ...
def svg_to_ico(input_path: Path, output_folder: Path):
    ...
def svg_to_cur(input_path: Path, output_folder: Path):
    ...
def webp_to_png(input_path: Path, output_folder: Path):
    ...
def webp_to_apng(input_path: Path, output_folder: Path):
    ...
def webp_to_jpg(input_path: Path, output_folder: Path):
    ...
def webp_to_jpeg(input_path: Path, output_folder: Path):
    ...
def webp_to_jfif(input_path: Path, output_folder: Path):
    ...
def webp_to_pjpeg(input_path: Path, output_folder: Path):
    ...
def webp_to_pjp(input_path: Path, output_folder: Path):
    ...
def webp_to_svg(input_path: Path, output_folder: Path):
    ...
def webp_to_gif(input_path: Path, output_folder: Path):
    ...
def webp_to_tif(input_path: Path, output_folder: Path):
    ...
def webp_to_tiff(input_path: Path, output_folder: Path):
    ...
def webp_to_bmp(input_path: Path, output_folder: Path):
    ...
def webp_to_eps(input_path: Path, output_folder: Path):
    ...
def webp_to_heic(input_path: Path, output_folder: Path):
    ...
def webp_to_avif(input_path: Path, output_folder: Path):
    ...
def webp_to_ico(input_path: Path, output_folder: Path):
    ...
def webp_to_cur(input_path: Path, output_folder: Path):
    ...
def gif_to_png(input_path: Path, output_folder: Path):
    ...
def gif_to_apng(input_path: Path, output_folder: Path):
    ...
def gif_to_jpg(input_path: Path, output_folder: Path):
    ...
def gif_to_jpeg(input_path: Path, output_folder: Path):
    ...
def gif_to_jfif(input_path: Path, output_folder: Path):
    ...
def gif_to_pjpeg(input_path: Path, output_folder: Path):
    ...
def gif_to_pjp(input_path: Path, output_folder: Path):
    ...
def gif_to_svg(input_path: Path, output_folder: Path):
    ...
def gif_to_webp(input_path: Path, output_folder: Path):
    ...
def gif_to_tif(input_path: Path, output_folder: Path):
    ...
def gif_to_tiff(input_path: Path, output_folder: Path):
    ...
def gif_to_bmp(input_path: Path, output_folder: Path):
    ...
def gif_to_eps(input_path: Path, output_folder: Path):
    ...
def gif_to_heic(input_path: Path, output_folder: Path):
    ...
def gif_to_avif(input_path: Path, output_folder: Path):
    ...
def gif_to_ico(input_path: Path, output_folder: Path):
    ...
def gif_to_cur(input_path: Path, output_folder: Path):
    ...
def tif_to_png(input_path: Path, output_folder: Path):
    ...
def tif_to_apng(input_path: Path, output_folder: Path):
    ...
def tif_to_jpg(input_path: Path, output_folder: Path):
    ...
def tif_to_jpeg(input_path: Path, output_folder: Path):
    ...
def tif_to_jfif(input_path: Path, output_folder: Path):
    ...
def tif_to_pjpeg(input_path: Path, output_folder: Path):
    ...
def tif_to_pjp(input_path: Path, output_folder: Path):
    ...
def tif_to_svg(input_path: Path, output_folder: Path):
    ...
def tif_to_webp(input_path: Path, output_folder: Path):
    ...
def tif_to_gif(input_path: Path, output_folder: Path):
    ...
def tif_to_tiff(input_path: Path, output_folder: Path):
    ...
def tif_to_bmp(input_path: Path, output_folder: Path):
    ...
def tif_to_eps(input_path: Path, output_folder: Path):
    ...
def tif_to_heic(input_path: Path, output_folder: Path):
    ...
def tif_to_avif(input_path: Path, output_folder: Path):
    ...
def tif_to_ico(input_path: Path, output_folder: Path):
    ...
def tif_to_cur(input_path: Path, output_folder: Path):
    ...
def tiff_to_png(input_path: Path, output_folder: Path):
    ...
def tiff_to_apng(input_path: Path, output_folder: Path):
    ...
def tiff_to_jpg(input_path: Path, output_folder: Path):
    ...
def tiff_to_jpeg(input_path: Path, output_folder: Path):
    ...
def tiff_to_jfif(input_path: Path, output_folder: Path):
    ...
def tiff_to_pjpeg(input_path: Path, output_folder: Path):
    ...
def tiff_to_pjp(input_path: Path, output_folder: Path):
    ...
def tiff_to_svg(input_path: Path, output_folder: Path):
    ...
def tiff_to_webp(input_path: Path, output_folder: Path):
    ...
def tiff_to_gif(input_path: Path, output_folder: Path):
    ...
def tiff_to_tif(input_path: Path, output_folder: Path):
    ...
def tiff_to_bmp(input_path: Path, output_folder: Path):
    ...
def tiff_to_eps(input_path: Path, output_folder: Path):
    ...
def tiff_to_heic(input_path: Path, output_folder: Path):
    ...
def tiff_to_avif(input_path: Path, output_folder: Path):
    ...
def tiff_to_ico(input_path: Path, output_folder: Path):
    ...
def tiff_to_cur(input_path: Path, output_folder: Path):
    ...
def bmp_to_png(input_path: Path, output_folder: Path):
    ...
def bmp_to_apng(input_path: Path, output_folder: Path):
    ...
def bmp_to_jpg(input_path: Path, output_folder: Path):
    ...
def bmp_to_jpeg(input_path: Path, output_folder: Path):
    ...
def bmp_to_jfif(input_path: Path, output_folder: Path):
    ...
def bmp_to_pjpeg(input_path: Path, output_folder: Path):
    ...
def bmp_to_pjp(input_path: Path, output_folder: Path):
    ...
def bmp_to_svg(input_path: Path, output_folder: Path):
    ...
def bmp_to_webp(input_path: Path, output_folder: Path):
    ...
def bmp_to_gif(input_path: Path, output_folder: Path):
    ...
def bmp_to_tif(input_path: Path, output_folder: Path):
    ...
def bmp_to_tiff(input_path: Path, output_folder: Path):
    ...
def bmp_to_eps(input_path: Path, output_folder: Path):
    ...
def bmp_to_heic(input_path: Path, output_folder: Path):
    ...
def bmp_to_avif(input_path: Path, output_folder: Path):
    ...
def bmp_to_ico(input_path: Path, output_folder: Path):
    ...
def bmp_to_cur(input_path: Path, output_folder: Path):
    ...
def eps_to_png(input_path: Path, output_folder: Path):
    ...
def eps_to_apng(input_path: Path, output_folder: Path):
    ...
def eps_to_jpg(input_path: Path, output_folder: Path):
    ...
def eps_to_jpeg(input_path: Path, output_folder: Path):
    ...
def eps_to_jfif(input_path: Path, output_folder: Path):
    ...
def eps_to_pjpeg(input_path: Path, output_folder: Path):
    ...
def eps_to_pjp(input_path: Path, output_folder: Path):
    ...
def eps_to_svg(input_path: Path, output_folder: Path):
    ...
def eps_to_webp(input_path: Path, output_folder: Path):
    ...
def eps_to_gif(input_path: Path, output_folder: Path):
    ...
def eps_to_tif(input_path: Path, output_folder: Path):
    ...
def eps_to_tiff(input_path: Path, output_folder: Path):
    ...
def eps_to_bmp(input_path: Path, output_folder: Path):
    ...
def eps_to_heic(input_path: Path, output_folder: Path):
    ...
def eps_to_avif(input_path: Path, output_folder: Path):
    ...
def eps_to_ico(input_path: Path, output_folder: Path):
    ...
def eps_to_cur(input_path: Path, output_folder: Path):
    ...
def heic_to_png(input_path: Path, output_folder: Path):
    ...
def heic_to_apng(input_path: Path, output_folder: Path):
    ...
def heic_to_jpg(input_path: Path, output_folder: Path):
    ...
def heic_to_jpeg(input_path: Path, output_folder: Path):
    ...
def heic_to_jfif(input_path: Path, output_folder: Path):
    ...
def heic_to_pjpeg(input_path: Path, output_folder: Path):
    ...
def heic_to_pjp(input_path: Path, output_folder: Path):
    ...
def heic_to_svg(input_path: Path, output_folder: Path):
    ...
def heic_to_webp(input_path: Path, output_folder: Path):
    ...
def heic_to_gif(input_path: Path, output_folder: Path):
    ...
def heic_to_tif(input_path: Path, output_folder: Path):
    ...
def heic_to_tiff(input_path: Path, output_folder: Path):
    ...
def heic_to_bmp(input_path: Path, output_folder: Path):
    ...
def heic_to_eps(input_path: Path, output_folder: Path):
    ...
def heic_to_avif(input_path: Path, output_folder: Path):
    ...
def heic_to_ico(input_path: Path, output_folder: Path):
    ...
def heic_to_cur(input_path: Path, output_folder: Path):
    ...
def avif_to_png(input_path: Path, output_folder: Path):
    ...
def avif_to_apng(input_path: Path, output_folder: Path):
    ...
def avif_to_jpg(input_path: Path, output_folder: Path):
    ...
def avif_to_jpeg(input_path: Path, output_folder: Path):
    ...
def avif_to_jfif(input_path: Path, output_folder: Path):
    ...
def avif_to_pjpeg(input_path: Path, output_folder: Path):
    ...
def avif_to_pjp(input_path: Path, output_folder: Path):
    ...
def avif_to_svg(input_path: Path, output_folder: Path):
    ...
def avif_to_webp(input_path: Path, output_folder: Path):
    ...
def avif_to_gif(input_path: Path, output_folder: Path):
    ...
def avif_to_tif(input_path: Path, output_folder: Path):
    ...
def avif_to_tiff(input_path: Path, output_folder: Path):
    ...
def avif_to_bmp(input_path: Path, output_folder: Path):
    ...
def avif_to_eps(input_path: Path, output_folder: Path):
    ...
def avif_to_heic(input_path: Path, output_folder: Path):
    ...
def avif_to_ico(input_path: Path, output_folder: Path):
    ...
def avif_to_cur(input_path: Path, output_folder: Path):
    ...
def ico_to_png(input_path: Path, output_folder: Path):
    ...
def ico_to_apng(input_path: Path, output_folder: Path):
    ...
def ico_to_jpg(input_path: Path, output_folder: Path):
    ...
def ico_to_jpeg(input_path: Path, output_folder: Path):
    ...
def ico_to_jfif(input_path: Path, output_folder: Path):
    ...
def ico_to_pjpeg(input_path: Path, output_folder: Path):
    ...
def ico_to_pjp(input_path: Path, output_folder: Path):
    ...
def ico_to_svg(input_path: Path, output_folder: Path):
    ...
def ico_to_webp(input_path: Path, output_folder: Path):
    ...
def ico_to_gif(input_path: Path, output_folder: Path):
    ...
def ico_to_tif(input_path: Path, output_folder: Path):
    ...
def ico_to_tiff(input_path: Path, output_folder: Path):
    ...
def ico_to_bmp(input_path: Path, output_folder: Path):
    ...
def ico_to_eps(input_path: Path, output_folder: Path):
    ...
def ico_to_heic(input_path: Path, output_folder: Path):
    ...
def ico_to_avif(input_path: Path, output_folder: Path):
    ...
def ico_to_cur(input_path: Path, output_folder: Path):
    ...
def cur_to_png(input_path: Path, output_folder: Path):
    ...
def cur_to_apng(input_path: Path, output_folder: Path):
    ...
def cur_to_jpg(input_path: Path, output_folder: Path):
    ...
def cur_to_jpeg(input_path: Path, output_folder: Path):
    ...
def cur_to_jfif(input_path: Path, output_folder: Path):
    ...
def cur_to_pjpeg(input_path: Path, output_folder: Path):
    ...
def cur_to_pjp(input_path: Path, output_folder: Path):
    ...
def cur_to_svg(input_path: Path, output_folder: Path):
    ...
def cur_to_webp(input_path: Path, output_folder: Path):
    ...
def cur_to_gif(input_path: Path, output_folder: Path):
    ...
def cur_to_tif(input_path: Path, output_folder: Path):
    ...
def cur_to_tiff(input_path: Path, output_folder: Path):
    ...
def cur_to_bmp(input_path: Path, output_folder: Path):
    ...
def cur_to_eps(input_path: Path, output_folder: Path):
    ...
def cur_to_heic(input_path: Path, output_folder: Path):
    ...
def cur_to_avif(input_path: Path, output_folder: Path):
    ...
def cur_to_ico(input_path: Path, output_folder: Path):
    ...

# --- doc ---


def asc_to_doc(input_path: Path, output_folder: Path):
    ...
def asc_to_docx(input_path: Path, output_folder: Path):
    ...
def asc_to_rtf(input_path: Path, output_folder: Path):
    ...
def asc_to_msg(input_path: Path, output_folder: Path):
    ...
def asc_to_pdf(input_path: Path, output_folder: Path):
    ...
def asc_to_txt(input_path: Path, output_folder: Path):
    ...
def asc_to_wpd(input_path: Path, output_folder: Path):
    ...
def asc_to_wps(input_path: Path, output_folder: Path):
    ...
def asc_to_csv(input_path: Path, output_folder: Path):
    ...
def asc_to_xlsx(input_path: Path, output_folder: Path):
    ...
def asc_to_json(input_path: Path, output_folder: Path):
    ...
def asc_to_html(input_path: Path, output_folder: Path):
    ...
def asc_to_htm(input_path: Path, output_folder: Path):
    ...
def asc_to_xhtml(input_path: Path, output_folder: Path):
    ...
def asc_to_asp(input_path: Path, output_folder: Path):
    ...
def asc_to_css(input_path: Path, output_folder: Path):
    ...
def asc_to_aspx(input_path: Path, output_folder: Path):
    ...
def asc_to_rss(input_path: Path, output_folder: Path):
    ...
def asc_to_pptx(input_path: Path, output_folder: Path):
    ...
def doc_to_asc(input_path: Path, output_folder: Path):
    ...
def doc_to_docx(input_path: Path, output_folder: Path):
    ...
def doc_to_rtf(input_path: Path, output_folder: Path):
    ...
def doc_to_msg(input_path: Path, output_folder: Path):
    ...
def doc_to_pdf(input_path: Path, output_folder: Path):
    ...
def doc_to_txt(input_path: Path, output_folder: Path):
    ...
def doc_to_wpd(input_path: Path, output_folder: Path):
    ...
def doc_to_wps(input_path: Path, output_folder: Path):
    ...
def doc_to_csv(input_path: Path, output_folder: Path):
    ...
def doc_to_xlsx(input_path: Path, output_folder: Path):
    ...
def doc_to_json(input_path: Path, output_folder: Path):
    ...
def doc_to_html(input_path: Path, output_folder: Path):
    ...
def doc_to_htm(input_path: Path, output_folder: Path):
    ...
def doc_to_xhtml(input_path: Path, output_folder: Path):
    ...
def doc_to_asp(input_path: Path, output_folder: Path):
    ...
def doc_to_css(input_path: Path, output_folder: Path):
    ...
def doc_to_aspx(input_path: Path, output_folder: Path):
    ...
def doc_to_rss(input_path: Path, output_folder: Path):
    ...
def doc_to_pptx(input_path: Path, output_folder: Path):
    ...
def docx_to_asc(input_path: Path, output_folder: Path):
    ...
def docx_to_doc(input_path: Path, output_folder: Path):
    ...
def docx_to_rtf(input_path: Path, output_folder: Path):
    ...
def docx_to_msg(input_path: Path, output_folder: Path):
    ...
def docx_to_pdf(input_path: Path, output_folder: Path):
    ...
def docx_to_txt(input_path: Path, output_folder: Path):
    ...
def docx_to_wpd(input_path: Path, output_folder: Path):
    ...
def docx_to_wps(input_path: Path, output_folder: Path):
    ...
def docx_to_csv(input_path: Path, output_folder: Path):
    ...
def docx_to_xlsx(input_path: Path, output_folder: Path):
    ...
def docx_to_json(input_path: Path, output_folder: Path):
    ...
def docx_to_html(input_path: Path, output_folder: Path):
    ...
def docx_to_htm(input_path: Path, output_folder: Path):
    ...
def docx_to_xhtml(input_path: Path, output_folder: Path):
    ...
def docx_to_asp(input_path: Path, output_folder: Path):
    ...
def docx_to_css(input_path: Path, output_folder: Path):
    ...
def docx_to_aspx(input_path: Path, output_folder: Path):
    ...
def docx_to_rss(input_path: Path, output_folder: Path):
    ...
def docx_to_pptx(input_path: Path, output_folder: Path):
    ...
def rtf_to_asc(input_path: Path, output_folder: Path):
    ...
def rtf_to_doc(input_path: Path, output_folder: Path):
    ...
def rtf_to_docx(input_path: Path, output_folder: Path):
    ...
def rtf_to_msg(input_path: Path, output_folder: Path):
    ...
def rtf_to_pdf(input_path: Path, output_folder: Path):
    ...
def rtf_to_txt(input_path: Path, output_folder: Path):
    ...
def rtf_to_wpd(input_path: Path, output_folder: Path):
    ...
def rtf_to_wps(input_path: Path, output_folder: Path):
    ...
def rtf_to_csv(input_path: Path, output_folder: Path):
    ...
def rtf_to_xlsx(input_path: Path, output_folder: Path):
    ...
def rtf_to_json(input_path: Path, output_folder: Path):
    ...
def rtf_to_html(input_path: Path, output_folder: Path):
    ...
def rtf_to_htm(input_path: Path, output_folder: Path):
    ...
def rtf_to_xhtml(input_path: Path, output_folder: Path):
    ...
def rtf_to_asp(input_path: Path, output_folder: Path):
    ...
def rtf_to_css(input_path: Path, output_folder: Path):
    ...
def rtf_to_aspx(input_path: Path, output_folder: Path):
    ...
def rtf_to_rss(input_path: Path, output_folder: Path):
    ...
def rtf_to_pptx(input_path: Path, output_folder: Path):
    ...
def msg_to_asc(input_path: Path, output_folder: Path):
    ...
def msg_to_doc(input_path: Path, output_folder: Path):
    ...
def msg_to_docx(input_path: Path, output_folder: Path):
    ...
def msg_to_rtf(input_path: Path, output_folder: Path):
    ...
def msg_to_pdf(input_path: Path, output_folder: Path):
    ...
def msg_to_txt(input_path: Path, output_folder: Path):
    ...
def msg_to_wpd(input_path: Path, output_folder: Path):
    ...
def msg_to_wps(input_path: Path, output_folder: Path):
    ...
def msg_to_csv(input_path: Path, output_folder: Path):
    ...
def msg_to_xlsx(input_path: Path, output_folder: Path):
    ...
def msg_to_json(input_path: Path, output_folder: Path):
    ...
def msg_to_html(input_path: Path, output_folder: Path):
    ...
def msg_to_htm(input_path: Path, output_folder: Path):
    ...
def msg_to_xhtml(input_path: Path, output_folder: Path):
    ...
def msg_to_asp(input_path: Path, output_folder: Path):
    ...
def msg_to_css(input_path: Path, output_folder: Path):
    ...
def msg_to_aspx(input_path: Path, output_folder: Path):
    ...
def msg_to_rss(input_path: Path, output_folder: Path):
    ...
def msg_to_pptx(input_path: Path, output_folder: Path):
    ...
def pdf_to_asc(input_path: Path, output_folder: Path):
    ...
def pdf_to_doc(input_path: Path, output_folder: Path):
    ...
def pdf_to_docx(input_path: Path, output_folder: Path):
    ...
def pdf_to_rtf(input_path: Path, output_folder: Path):
    ...
def pdf_to_msg(input_path: Path, output_folder: Path):
    ...
def pdf_to_txt(input_path: Path, output_folder: Path):
    ...
def pdf_to_wpd(input_path: Path, output_folder: Path):
    ...
def pdf_to_wps(input_path: Path, output_folder: Path):
    ...
def pdf_to_csv(input_path: Path, output_folder: Path):
    ...
def pdf_to_xlsx(input_path: Path, output_folder: Path):
    ...
def pdf_to_json(input_path: Path, output_folder: Path):
    ...
def pdf_to_html(input_path: Path, output_folder: Path):
    ...
def pdf_to_htm(input_path: Path, output_folder: Path):
    ...
def pdf_to_xhtml(input_path: Path, output_folder: Path):
    ...
def pdf_to_asp(input_path: Path, output_folder: Path):
    ...
def pdf_to_css(input_path: Path, output_folder: Path):
    ...
def pdf_to_aspx(input_path: Path, output_folder: Path):
    ...
def pdf_to_rss(input_path: Path, output_folder: Path):
    ...
def pdf_to_pptx(input_path: Path, output_folder: Path):
    ...
def txt_to_asc(input_path: Path, output_folder: Path):
    ...
def txt_to_doc(input_path: Path, output_folder: Path):
    ...
def txt_to_docx(input_path: Path, output_folder: Path):
    ...
def txt_to_rtf(input_path: Path, output_folder: Path):
    ...
def txt_to_msg(input_path: Path, output_folder: Path):
    ...
def txt_to_pdf(input_path: Path, output_folder: Path):
    ...
def txt_to_wpd(input_path: Path, output_folder: Path):
    ...
def txt_to_wps(input_path: Path, output_folder: Path):
    ...
def txt_to_csv(input_path: Path, output_folder: Path):
    ...
def txt_to_xlsx(input_path: Path, output_folder: Path):
    ...
def txt_to_json(input_path: Path, output_folder: Path):
    ...
def txt_to_html(input_path: Path, output_folder: Path):
    ...
def txt_to_htm(input_path: Path, output_folder: Path):
    ...
def txt_to_xhtml(input_path: Path, output_folder: Path):
    ...
def txt_to_asp(input_path: Path, output_folder: Path):
    ...
def txt_to_css(input_path: Path, output_folder: Path):
    ...
def txt_to_aspx(input_path: Path, output_folder: Path):
    ...
def txt_to_rss(input_path: Path, output_folder: Path):
    ...
def txt_to_pptx(input_path: Path, output_folder: Path):
    ...
def wpd_to_asc(input_path: Path, output_folder: Path):
    ...
def wpd_to_doc(input_path: Path, output_folder: Path):
    ...
def wpd_to_docx(input_path: Path, output_folder: Path):
    ...
def wpd_to_rtf(input_path: Path, output_folder: Path):
    ...
def wpd_to_msg(input_path: Path, output_folder: Path):
    ...
def wpd_to_pdf(input_path: Path, output_folder: Path):
    ...
def wpd_to_txt(input_path: Path, output_folder: Path):
    ...
def wpd_to_wps(input_path: Path, output_folder: Path):
    ...
def wpd_to_csv(input_path: Path, output_folder: Path):
    ...
def wpd_to_xlsx(input_path: Path, output_folder: Path):
    ...
def wpd_to_json(input_path: Path, output_folder: Path):
    ...
def wpd_to_html(input_path: Path, output_folder: Path):
    ...
def wpd_to_htm(input_path: Path, output_folder: Path):
    ...
def wpd_to_xhtml(input_path: Path, output_folder: Path):
    ...
def wpd_to_asp(input_path: Path, output_folder: Path):
    ...
def wpd_to_css(input_path: Path, output_folder: Path):
    ...
def wpd_to_aspx(input_path: Path, output_folder: Path):
    ...
def wpd_to_rss(input_path: Path, output_folder: Path):
    ...
def wpd_to_pptx(input_path: Path, output_folder: Path):
    ...
def wps_to_asc(input_path: Path, output_folder: Path):
    ...
def wps_to_doc(input_path: Path, output_folder: Path):
    ...
def wps_to_docx(input_path: Path, output_folder: Path):
    ...
def wps_to_rtf(input_path: Path, output_folder: Path):
    ...
def wps_to_msg(input_path: Path, output_folder: Path):
    ...
def wps_to_pdf(input_path: Path, output_folder: Path):
    ...
def wps_to_txt(input_path: Path, output_folder: Path):
    ...
def wps_to_wpd(input_path: Path, output_folder: Path):
    ...
def wps_to_csv(input_path: Path, output_folder: Path):
    ...
def wps_to_xlsx(input_path: Path, output_folder: Path):
    ...
def wps_to_json(input_path: Path, output_folder: Path):
    ...
def wps_to_html(input_path: Path, output_folder: Path):
    ...
def wps_to_htm(input_path: Path, output_folder: Path):
    ...
def wps_to_xhtml(input_path: Path, output_folder: Path):
    ...
def wps_to_asp(input_path: Path, output_folder: Path):
    ...
def wps_to_css(input_path: Path, output_folder: Path):
    ...
def wps_to_aspx(input_path: Path, output_folder: Path):
    ...
def wps_to_rss(input_path: Path, output_folder: Path):
    ...
def wps_to_pptx(input_path: Path, output_folder: Path):
    ...
def csv_to_asc(input_path: Path, output_folder: Path):
    ...
def csv_to_doc(input_path: Path, output_folder: Path):
    ...
def csv_to_docx(input_path: Path, output_folder: Path):
    ...
def csv_to_rtf(input_path: Path, output_folder: Path):
    ...
def csv_to_msg(input_path: Path, output_folder: Path):
    ...
def csv_to_pdf(input_path: Path, output_folder: Path):
    ...
def csv_to_txt(input_path: Path, output_folder: Path):
    ...
def csv_to_wpd(input_path: Path, output_folder: Path):
    ...
def csv_to_wps(input_path: Path, output_folder: Path):
    ...
def csv_to_xlsx(input_path: Path, output_folder: Path):
    ...
def csv_to_json(input_path: Path, output_folder: Path):
    ...
def csv_to_html(input_path: Path, output_folder: Path):
    ...
def csv_to_htm(input_path: Path, output_folder: Path):
    ...
def csv_to_xhtml(input_path: Path, output_folder: Path):
    ...
def csv_to_asp(input_path: Path, output_folder: Path):
    ...
def csv_to_css(input_path: Path, output_folder: Path):
    ...
def csv_to_aspx(input_path: Path, output_folder: Path):
    ...
def csv_to_rss(input_path: Path, output_folder: Path):
    ...
def csv_to_pptx(input_path: Path, output_folder: Path):
    ...
def xlsx_to_asc(input_path: Path, output_folder: Path):
    ...
def xlsx_to_doc(input_path: Path, output_folder: Path):
    ...
def xlsx_to_docx(input_path: Path, output_folder: Path):
    ...
def xlsx_to_rtf(input_path: Path, output_folder: Path):
    ...
def xlsx_to_msg(input_path: Path, output_folder: Path):
    ...
def xlsx_to_pdf(input_path: Path, output_folder: Path):
    print('success')
def xlsx_to_txt(input_path: Path, output_folder: Path):
    ...
def xlsx_to_wpd(input_path: Path, output_folder: Path):
    ...
def xlsx_to_wps(input_path: Path, output_folder: Path):
    ...
def xlsx_to_csv(input_path: Path, output_folder: Path):
    ...
def xlsx_to_json(input_path: Path, output_folder: Path):
    ...
def xlsx_to_html(input_path: Path, output_folder: Path):
    ...
def xlsx_to_htm(input_path: Path, output_folder: Path):
    ...
def xlsx_to_xhtml(input_path: Path, output_folder: Path):
    ...
def xlsx_to_asp(input_path: Path, output_folder: Path):
    ...
def xlsx_to_css(input_path: Path, output_folder: Path):
    ...
def xlsx_to_aspx(input_path: Path, output_folder: Path):
    ...
def xlsx_to_rss(input_path: Path, output_folder: Path):
    ...
def xlsx_to_pptx(input_path: Path, output_folder: Path):
    ...
def json_to_asc(input_path: Path, output_folder: Path):
    ...
def json_to_doc(input_path: Path, output_folder: Path):
    ...
def json_to_docx(input_path: Path, output_folder: Path):
    ...
def json_to_rtf(input_path: Path, output_folder: Path):
    ...
def json_to_msg(input_path: Path, output_folder: Path):
    ...
def json_to_pdf(input_path: Path, output_folder: Path):
    ...
def json_to_txt(input_path: Path, output_folder: Path):
    ...
def json_to_wpd(input_path: Path, output_folder: Path):
    ...
def json_to_wps(input_path: Path, output_folder: Path):
    ...
def json_to_csv(input_path: Path, output_folder: Path):
    ...
def json_to_xlsx(input_path: Path, output_folder: Path):
    ...
def json_to_html(input_path: Path, output_folder: Path):
    ...
def json_to_htm(input_path: Path, output_folder: Path):
    ...
def json_to_xhtml(input_path: Path, output_folder: Path):
    ...
def json_to_asp(input_path: Path, output_folder: Path):
    ...
def json_to_css(input_path: Path, output_folder: Path):
    ...
def json_to_aspx(input_path: Path, output_folder: Path):
    ...
def json_to_rss(input_path: Path, output_folder: Path):
    ...
def json_to_pptx(input_path: Path, output_folder: Path):
    ...
def html_to_asc(input_path: Path, output_folder: Path):
    ...
def html_to_doc(input_path: Path, output_folder: Path):
    ...
def html_to_docx(input_path: Path, output_folder: Path):
    ...
def html_to_rtf(input_path: Path, output_folder: Path):
    ...
def html_to_msg(input_path: Path, output_folder: Path):
    ...
def html_to_pdf(input_path: Path, output_folder: Path):
    ...
def html_to_txt(input_path: Path, output_folder: Path):
    ...
def html_to_wpd(input_path: Path, output_folder: Path):
    ...
def html_to_wps(input_path: Path, output_folder: Path):
    ...
def html_to_csv(input_path: Path, output_folder: Path):
    ...
def html_to_xlsx(input_path: Path, output_folder: Path):
    ...
def html_to_json(input_path: Path, output_folder: Path):
    ...
def html_to_htm(input_path: Path, output_folder: Path):
    ...
def html_to_xhtml(input_path: Path, output_folder: Path):
    ...
def html_to_asp(input_path: Path, output_folder: Path):
    ...
def html_to_css(input_path: Path, output_folder: Path):
    ...
def html_to_aspx(input_path: Path, output_folder: Path):
    ...
def html_to_rss(input_path: Path, output_folder: Path):
    ...
def html_to_pptx(input_path: Path, output_folder: Path):
    ...
def htm_to_asc(input_path: Path, output_folder: Path):
    ...
def htm_to_doc(input_path: Path, output_folder: Path):
    ...
def htm_to_docx(input_path: Path, output_folder: Path):
    ...
def htm_to_rtf(input_path: Path, output_folder: Path):
    ...
def htm_to_msg(input_path: Path, output_folder: Path):
    ...
def htm_to_pdf(input_path: Path, output_folder: Path):
    ...
def htm_to_txt(input_path: Path, output_folder: Path):
    ...
def htm_to_wpd(input_path: Path, output_folder: Path):
    ...
def htm_to_wps(input_path: Path, output_folder: Path):
    ...
def htm_to_csv(input_path: Path, output_folder: Path):
    ...
def htm_to_xlsx(input_path: Path, output_folder: Path):
    ...
def htm_to_json(input_path: Path, output_folder: Path):
    ...
def htm_to_html(input_path: Path, output_folder: Path):
    ...
def htm_to_xhtml(input_path: Path, output_folder: Path):
    ...
def htm_to_asp(input_path: Path, output_folder: Path):
    ...
def htm_to_css(input_path: Path, output_folder: Path):
    ...
def htm_to_aspx(input_path: Path, output_folder: Path):
    ...
def htm_to_rss(input_path: Path, output_folder: Path):
    ...
def htm_to_pptx(input_path: Path, output_folder: Path):
    ...
def xhtml_to_asc(input_path: Path, output_folder: Path):
    ...
def xhtml_to_doc(input_path: Path, output_folder: Path):
    ...
def xhtml_to_docx(input_path: Path, output_folder: Path):
    ...
def xhtml_to_rtf(input_path: Path, output_folder: Path):
    ...
def xhtml_to_msg(input_path: Path, output_folder: Path):
    ...
def xhtml_to_pdf(input_path: Path, output_folder: Path):
    ...
def xhtml_to_txt(input_path: Path, output_folder: Path):
    ...
def xhtml_to_wpd(input_path: Path, output_folder: Path):
    ...
def xhtml_to_wps(input_path: Path, output_folder: Path):
    ...
def xhtml_to_csv(input_path: Path, output_folder: Path):
    ...
def xhtml_to_xlsx(input_path: Path, output_folder: Path):
    ...
def xhtml_to_json(input_path: Path, output_folder: Path):
    ...
def xhtml_to_html(input_path: Path, output_folder: Path):
    ...
def xhtml_to_htm(input_path: Path, output_folder: Path):
    ...
def xhtml_to_asp(input_path: Path, output_folder: Path):
    ...
def xhtml_to_css(input_path: Path, output_folder: Path):
    ...
def xhtml_to_aspx(input_path: Path, output_folder: Path):
    ...
def xhtml_to_rss(input_path: Path, output_folder: Path):
    ...
def xhtml_to_pptx(input_path: Path, output_folder: Path):
    ...
def asp_to_asc(input_path: Path, output_folder: Path):
    ...
def asp_to_doc(input_path: Path, output_folder: Path):
    ...
def asp_to_docx(input_path: Path, output_folder: Path):
    ...
def asp_to_rtf(input_path: Path, output_folder: Path):
    ...
def asp_to_msg(input_path: Path, output_folder: Path):
    ...
def asp_to_pdf(input_path: Path, output_folder: Path):
    ...
def asp_to_txt(input_path: Path, output_folder: Path):
    ...
def asp_to_wpd(input_path: Path, output_folder: Path):
    ...
def asp_to_wps(input_path: Path, output_folder: Path):
    ...
def asp_to_csv(input_path: Path, output_folder: Path):
    ...
def asp_to_xlsx(input_path: Path, output_folder: Path):
    ...
def asp_to_json(input_path: Path, output_folder: Path):
    ...
def asp_to_html(input_path: Path, output_folder: Path):
    ...
def asp_to_htm(input_path: Path, output_folder: Path):
    ...
def asp_to_xhtml(input_path: Path, output_folder: Path):
    ...
def asp_to_css(input_path: Path, output_folder: Path):
    ...
def asp_to_aspx(input_path: Path, output_folder: Path):
    ...
def asp_to_rss(input_path: Path, output_folder: Path):
    ...
def asp_to_pptx(input_path: Path, output_folder: Path):
    ...
def css_to_asc(input_path: Path, output_folder: Path):
    ...
def css_to_doc(input_path: Path, output_folder: Path):
    ...
def css_to_docx(input_path: Path, output_folder: Path):
    ...
def css_to_rtf(input_path: Path, output_folder: Path):
    ...
def css_to_msg(input_path: Path, output_folder: Path):
    ...
def css_to_pdf(input_path: Path, output_folder: Path):
    ...
def css_to_txt(input_path: Path, output_folder: Path):
    ...
def css_to_wpd(input_path: Path, output_folder: Path):
    ...
def css_to_wps(input_path: Path, output_folder: Path):
    ...
def css_to_csv(input_path: Path, output_folder: Path):
    ...
def css_to_xlsx(input_path: Path, output_folder: Path):
    ...
def css_to_json(input_path: Path, output_folder: Path):
    ...
def css_to_html(input_path: Path, output_folder: Path):
    ...
def css_to_htm(input_path: Path, output_folder: Path):
    ...
def css_to_xhtml(input_path: Path, output_folder: Path):
    ...
def css_to_asp(input_path: Path, output_folder: Path):
    ...
def css_to_aspx(input_path: Path, output_folder: Path):
    ...
def css_to_rss(input_path: Path, output_folder: Path):
    ...
def css_to_pptx(input_path: Path, output_folder: Path):
    ...
def aspx_to_asc(input_path: Path, output_folder: Path):
    ...
def aspx_to_doc(input_path: Path, output_folder: Path):
    ...
def aspx_to_docx(input_path: Path, output_folder: Path):
    ...
def aspx_to_rtf(input_path: Path, output_folder: Path):
    ...
def aspx_to_msg(input_path: Path, output_folder: Path):
    ...
def aspx_to_pdf(input_path: Path, output_folder: Path):
    ...
def aspx_to_txt(input_path: Path, output_folder: Path):
    ...
def aspx_to_wpd(input_path: Path, output_folder: Path):
    ...
def aspx_to_wps(input_path: Path, output_folder: Path):
    ...
def aspx_to_csv(input_path: Path, output_folder: Path):
    ...
def aspx_to_xlsx(input_path: Path, output_folder: Path):
    ...
def aspx_to_json(input_path: Path, output_folder: Path):
    ...
def aspx_to_html(input_path: Path, output_folder: Path):
    ...
def aspx_to_htm(input_path: Path, output_folder: Path):
    ...
def aspx_to_xhtml(input_path: Path, output_folder: Path):
    ...
def aspx_to_asp(input_path: Path, output_folder: Path):
    ...
def aspx_to_css(input_path: Path, output_folder: Path):
    ...
def aspx_to_rss(input_path: Path, output_folder: Path):
    ...
def aspx_to_pptx(input_path: Path, output_folder: Path):
    ...
def rss_to_asc(input_path: Path, output_folder: Path):
    ...
def rss_to_doc(input_path: Path, output_folder: Path):
    ...
def rss_to_docx(input_path: Path, output_folder: Path):
    ...
def rss_to_rtf(input_path: Path, output_folder: Path):
    ...
def rss_to_msg(input_path: Path, output_folder: Path):
    ...
def rss_to_pdf(input_path: Path, output_folder: Path):
    ...
def rss_to_txt(input_path: Path, output_folder: Path):
    ...
def rss_to_wpd(input_path: Path, output_folder: Path):
    ...
def rss_to_wps(input_path: Path, output_folder: Path):
    ...
def rss_to_csv(input_path: Path, output_folder: Path):
    ...
def rss_to_xlsx(input_path: Path, output_folder: Path):
    ...
def rss_to_json(input_path: Path, output_folder: Path):
    ...
def rss_to_html(input_path: Path, output_folder: Path):
    ...
def rss_to_htm(input_path: Path, output_folder: Path):
    ...
def rss_to_xhtml(input_path: Path, output_folder: Path):
    ...
def rss_to_asp(input_path: Path, output_folder: Path):
    ...
def rss_to_css(input_path: Path, output_folder: Path):
    ...
def rss_to_aspx(input_path: Path, output_folder: Path):
    ...
def rss_to_pptx(input_path: Path, output_folder: Path):
    ...
def pptx_to_asc(input_path: Path, output_folder: Path):
    ...
def pptx_to_doc(input_path: Path, output_folder: Path):
    ...
def pptx_to_docx(input_path: Path, output_folder: Path):
    ...
def pptx_to_rtf(input_path: Path, output_folder: Path):
    ...
def pptx_to_msg(input_path: Path, output_folder: Path):
    ...
def pptx_to_pdf(input_path: Path, output_folder: Path):
    ...
def pptx_to_txt(input_path: Path, output_folder: Path):
    ...
def pptx_to_wpd(input_path: Path, output_folder: Path):
    ...
def pptx_to_wps(input_path: Path, output_folder: Path):
    ...
def pptx_to_csv(input_path: Path, output_folder: Path):
    ...
def pptx_to_xlsx(input_path: Path, output_folder: Path):
    ...
def pptx_to_json(input_path: Path, output_folder: Path):
    ...
def pptx_to_html(input_path: Path, output_folder: Path):
    ...
def pptx_to_htm(input_path: Path, output_folder: Path):
    ...
def pptx_to_xhtml(input_path: Path, output_folder: Path):
    ...
def pptx_to_asp(input_path: Path, output_folder: Path):
    ...
def pptx_to_css(input_path: Path, output_folder: Path):
    ...
def pptx_to_aspx(input_path: Path, output_folder: Path):
    ...
def pptx_to_rss(input_path: Path, output_folder: Path):
    ...


# --- aud ---


def mp3_to_wma(input_path: Path, output_folder: Path):
    ...
def mp3_to_snd(input_path: Path, output_folder: Path):
    ...
def mp3_to_wav(input_path: Path, output_folder: Path):
    ...
def mp3_to_ra(input_path: Path, output_folder: Path):
    ...
def mp3_to_au(input_path: Path, output_folder: Path):
    ...
def mp3_to_aac(input_path: Path, output_folder: Path):
    ...
def wma_to_mp3(input_path: Path, output_folder: Path):
    ...
def wma_to_snd(input_path: Path, output_folder: Path):
    ...
def wma_to_wav(input_path: Path, output_folder: Path):
    ...
def wma_to_ra(input_path: Path, output_folder: Path):
    ...
def wma_to_au(input_path: Path, output_folder: Path):
    ...
def wma_to_aac(input_path: Path, output_folder: Path):
    ...
def snd_to_mp3(input_path: Path, output_folder: Path):
    ...
def snd_to_wma(input_path: Path, output_folder: Path):
    ...
def snd_to_wav(input_path: Path, output_folder: Path):
    ...
def snd_to_ra(input_path: Path, output_folder: Path):
    ...
def snd_to_au(input_path: Path, output_folder: Path):
    ...
def snd_to_aac(input_path: Path, output_folder: Path):
    ...
def wav_to_mp3(input_path: Path, output_folder: Path):
    ...
def wav_to_wma(input_path: Path, output_folder: Path):
    ...
def wav_to_snd(input_path: Path, output_folder: Path):
    ...
def wav_to_ra(input_path: Path, output_folder: Path):
    ...
def wav_to_au(input_path: Path, output_folder: Path):
    ...
def wav_to_aac(input_path: Path, output_folder: Path):
    ...
def ra_to_mp3(input_path: Path, output_folder: Path):
    ...
def ra_to_wma(input_path: Path, output_folder: Path):
    ...
def ra_to_snd(input_path: Path, output_folder: Path):
    ...
def ra_to_wav(input_path: Path, output_folder: Path):
    ...
def ra_to_au(input_path: Path, output_folder: Path):
    ...
def ra_to_aac(input_path: Path, output_folder: Path):
    ...
def au_to_mp3(input_path: Path, output_folder: Path):
    ...
def au_to_wma(input_path: Path, output_folder: Path):
    ...
def au_to_snd(input_path: Path, output_folder: Path):
    ...
def au_to_wav(input_path: Path, output_folder: Path):
    ...
def au_to_ra(input_path: Path, output_folder: Path):
    ...
def au_to_aac(input_path: Path, output_folder: Path):
    ...
def aac_to_mp3(input_path: Path, output_folder: Path):
    ...
def aac_to_wma(input_path: Path, output_folder: Path):
    ...
def aac_to_snd(input_path: Path, output_folder: Path):
    ...
def aac_to_wav(input_path: Path, output_folder: Path):
    ...
def aac_to_ra(input_path: Path, output_folder: Path):
    ...
def aac_to_au(input_path: Path, output_folder: Path):
    ...


# --- vid ---


def mp4_to_3gp(input_path: Path, output_folder: Path):
    ...
def mp4_to_avi(input_path: Path, output_folder: Path):
    ...
def mp4_to_mpg(input_path: Path, output_folder: Path):
    ...
def mp4_to_mov(input_path: Path, output_folder: Path):
    ...
def mp4_to_wmv(input_path: Path, output_folder: Path):
    ...
def _3gp_to_mp4(input_path: Path, output_folder: Path):
    ...
def _3gp_to_avi(input_path: Path, output_folder: Path):
    ...
def _3gp_to_mpg(input_path: Path, output_folder: Path):
    ...
def _3gp_to_mov(input_path: Path, output_folder: Path):
    ...
def _3gp_to_wmv(input_path: Path, output_folder: Path):
    ...
def avi_to_mp4(input_path: Path, output_folder: Path):
    ...
def avi_to_3gp(input_path: Path, output_folder: Path):
    ...
def avi_to_mpg(input_path: Path, output_folder: Path):
    ...
def avi_to_mov(input_path: Path, output_folder: Path):
    ...
def avi_to_wmv(input_path: Path, output_folder: Path):
    ...
def mpg_to_mp4(input_path: Path, output_folder: Path):
    ...
def mpg_to_3gp(input_path: Path, output_folder: Path):
    ...
def mpg_to_avi(input_path: Path, output_folder: Path):
    ...
def mpg_to_mov(input_path: Path, output_folder: Path):
    ...
def mpg_to_wmv(input_path: Path, output_folder: Path):
    ...
def mov_to_mp4(input_path: Path, output_folder: Path):
    ...
def mov_to_3gp(input_path: Path, output_folder: Path):
    ...
def mov_to_avi(input_path: Path, output_folder: Path):
    ...
def mov_to_mpg(input_path: Path, output_folder: Path):
    ...
def mov_to_wmv(input_path: Path, output_folder: Path):
    ...
def wmv_to_mp4(input_path: Path, output_folder: Path):
    ...
def wmv_to_3gp(input_path: Path, output_folder: Path):
    ...
def wmv_to_avi(input_path: Path, output_folder: Path):
    ...
def wmv_to_mpg(input_path: Path, output_folder: Path):
    ...
def wmv_to_mov(input_path: Path, output_folder: Path):
    ...


if __name__ == "__main__":
    main()
